version: "3.2"

services:
  scouter-paper:
    image: <aws account id>.dkr.ecr.<region>.amazonaws.com/<ecr repo name>:scouter_paper_v2.6.4
    container_name: scouter-paper
    pull_policy: if_not_present
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
